// Copyright © 2015 Abhishek Banthia

import Cocoa

let CLEmptyString = ""
let CLDefaultPreferenceKey = "defaultPreferences"
let CLTimezoneName = "formattedAddress"
let CLCustomLabel = "customLabel"
let CL24hourFormatSelectedKey = "is24HourFormatSelected"
let CLDragSessionKey = "public.text"
let CLTimezoneID = "timezoneID"
let CLPlaceIdentifier = "place_id"
let CLRelativeDateKey = "relativeDate"
let CLThemeKey = "defaultTheme"
let CLShowDayInMenu = "showDay"
let CLShowDateInMenu = "showDate"
let CLShowPlaceInMenu = "showPlaceName"
let CLDisplayFutureSliderKey = "displayFutureSlider"
let CLStartAtLogin = "startAtLogin"
let CLShowAppInForeground = "displayAppAsForegroundApp"
let CLSunriseSunsetTime = "showSunriseSetTime"
let CLShowSecondsInMenubar = "showSeconds"
let CLUserFontSizePreference = "userFontSize"
let CLShowUpcomingEventView = "ShowUpcomingEventView"
let CLShowAllDayEventsInUpcomingView = "showAllDayEventsInUpcomingView"
let CLShowMeetingInMenubar = "showMeetingInfoInMenubar"
let CLTruncateTextLength = "truncateTextLength"
let CLFutureSliderRange = "sliderDayRange"
let CLSelectedCalendars = "SelectedCalendars"
let CLShowOnboardingFlow = "com.abhishek.showOnboardingFlow"
let CLAppDislayOptions = "com.abhishek.appDisplayOptions"
let CLLongStatusBarWarningMessage = "com.abhishek.longStatusBarWarning"
let CLUITestingLaunchArgument = "isUITesting"
let CLOnboaringTestsLaunchArgument = "isTestingTheOnboardingFlow"
let CLMenubarCompactMode = "com.abhishek.menubarCompactMode"
let CLDefaultMenubarMode = "com.abhishek.shouldDefaultToCompactMode"
let CLInstallHomeIndicatorObject = "installHomeIndicatorObject"
let CLDefaultThemeOnMojave = "com.abhishek.defaultHasBeenSetOnMacOsMojave"
let CLSwitchToCompactModeAlert = "com.abhishek.switchToCompactMode"
let CLGeocodingKey = "AIzaSyCyf2knCi6KiKuDJLYDBD3Odq5dt4c-_KI"
